/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/meta/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is alive */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                            /** @example watchman-backend-v2 */
                            service: string;
                            /** @description Seconds since process start */
                            uptime: number;
                            /** Format: date-time */
                            timestamp: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version info */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            version: string;
                            /** @example v20.10.0 */
                            node: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregated health for all registered services */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["AggregatedEntry"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/{kind}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health snapshot for a specific service instance */
        get: {
            parameters: {
                query?: {
                    /** @description Instance id. Omit to use first registered instance for the kind. */
                    instance?: components["parameters"]["Instance"];
                };
                header?: never;
                path: {
                    /** @description Service kind (e.g. bitcoin, ipfs, homebridge) */
                    kind: components["parameters"]["Kind"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["HealthSnapshot"];
                        };
                    };
                };
                404: components["responses"]["DomainError"];
                503: components["responses"]["DomainError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/{kind}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats snapshot for a specific service instance */
        get: {
            parameters: {
                query?: {
                    /** @description Instance id. Omit to use first registered instance for the kind. */
                    instance?: components["parameters"]["Instance"];
                };
                header?: never;
                path: {
                    /** @description Service kind (e.g. bitcoin, ipfs, homebridge) */
                    kind: components["parameters"]["Kind"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["StatsSnapshot"];
                        };
                    };
                };
                404: components["responses"]["DomainError"];
                503: components["responses"]["DomainError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/{kind}/control": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue a control action to a service instance */
        post: {
            parameters: {
                query?: {
                    /** @description Instance id. Omit to use first registered instance for the kind. */
                    instance?: components["parameters"]["Instance"];
                };
                header?: never;
                path: {
                    /** @description Service kind (e.g. bitcoin, ipfs, homebridge) */
                    kind: components["parameters"]["Kind"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example restart */
                        action: string;
                    };
                };
            };
            responses: {
                /** @description Action accepted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                ok: boolean;
                            };
                        };
                    };
                };
                400: components["responses"]["DomainError"];
                404: components["responses"]["DomainError"];
                503: components["responses"]["DomainError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All registered service instances */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["InstanceInfo"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Instances for a given service kind */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Service kind (e.g. bitcoin, ipfs, homebridge) */
                    kind: components["parameters"]["Kind"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["InstanceInfo"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kinds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All registered service kinds */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Operational metrics snapshot (breakers, poller, cache, process) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MetricsSnapshot"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Setup mode status (needs wizard?) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["SetupStatus"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/philips-bridge/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pair with a Philips Hue Bridge (press-link wizard)
         * @description Press the physical link button on the bridge, then call this endpoint.
         *     Simultaneously probes the TLS certificate SHA-256 fingerprint and posts to the
         *     bridge `/api` endpoint to obtain an application key.
         *     Returns `applicationKey` and `certHash` for use in the service configuration.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description IP or hostname of the Hue bridge */
                        host: string;
                        /**
                         * @description Request timeout in milliseconds
                         * @default 10000
                         */
                        timeoutMs?: number;
                    };
                };
            };
            responses: {
                /** @description Pairing successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description Hue API v2 application key (username) */
                                applicationKey: string;
                                /** @description SHA-256 fingerprint of the bridge TLS certificate (hex) */
                                certHash: string;
                            };
                        };
                    };
                };
                /** @description Missing host or link button not pressed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DomainError"];
                    };
                };
                /** @description Bridge unreachable or connection error */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DomainError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/kinds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Registered service kinds with Zod-derived field metadata for form rendering */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["KindSchema"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All configured service instances (secrets redacted) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["ServiceInstance"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a service instance */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ServiceInstanceInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["ServiceInstance"];
                        };
                    };
                };
                400: components["responses"]["DomainError"];
                409: components["responses"]["DomainError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/services/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Single service instance (secrets redacted) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["ServiceInstance"];
                        };
                    };
                };
                404: components["responses"]["DomainError"];
            };
        };
        /**
         * Update service instance. Secret fields sent as "***" preserve existing value.
         *     The `instanceId` may be changed; renames are validated against
         *     `^[a-z0-9][a-z0-9-]*$` (max 64 chars), checked for uniqueness within the
         *     same kind, recorded as a dedicated `rename` audit row, and broadcast as
         *     a `config:service.renamed` event. Returns 400 on a conflicting or
         *     malformed instanceId.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ServiceInstanceInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["ServiceInstance"];
                        };
                    };
                };
                400: components["responses"]["DomainError"];
                404: components["responses"]["DomainError"];
            };
        };
        post?: never;
        /** Delete a service instance */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["DomainError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/services/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run test-connection probe against a live service instance */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["TestConnectionResult"];
                        };
                    };
                };
                404: components["responses"]["DomainError"];
                409: components["responses"]["DomainError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Config audit timeline (most recent first) */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["AuditEntry"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export all service configurations as encrypted bundle */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Encrypted bundle (payload is base64 AES-256-GCM of plaintext services) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExportBundle"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import a previously exported bundle; upserts by (kind, instanceId) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExportBundle"];
                };
            };
            responses: {
                /** @description Import result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["ImportResult"];
                        };
                    };
                };
                /** @description Invalid bundle */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DomainError: {
            error: {
                /** @enum {string} */
                code: "NOT_FOUND" | "UNAVAILABLE" | "UNAUTHORIZED" | "TIMEOUT" | "CIRCUIT_OPEN" | "VALIDATION";
                message: string;
            };
        };
        HostHealth: {
            /** @description ICMP ping succeeded */
            reachable: boolean;
            /** @description Round-trip time in milliseconds */
            pingMs?: number;
        };
        ServiceHealth: {
            /** @description Service protocol probe succeeded */
            reachable: boolean;
            /** @description Protocol probe latency in milliseconds */
            latencyMs?: number;
            /** @description Human-readable failure reason */
            message?: string;
            /** @description Service-specific diagnostic details */
            details?: {
                [key: string]: unknown;
            };
        };
        HealthSnapshot: {
            /** @description Composite: host AND service reachable */
            reachable: boolean;
            /** @description Service latency, falls back to ping latency */
            latencyMs?: number;
            message?: string;
            details?: {
                [key: string]: unknown;
            };
            /** @description Timestamp (ms) when snapshot was taken */
            at: number;
            /** @description ICMP reachability tier */
            host?: components["schemas"]["HostHealth"];
            /** @description Protocol probe tier */
            service?: components["schemas"]["ServiceHealth"];
        };
        StatsSnapshot: {
            /**
             * @description Service-specific metrics. Keys and types vary by service kind.
             *     See service integration docs for metric details:
             *     - **Bitcoin** (BT1, BT2): blocks, difficulty, connections, mempool metrics (BT1); zmqLastBlockHash, zmqLastBlockAt, zmqBlockCount when zmqHashblockEndpoint configured (BT2 — real-time ZMQ)
             *     - **Raspberry Pi** (PI1): cpuTemp (°C), clockRate (MHz), voltage (V), throttled (0=healthy, non-zero=throttling/undervoltage), load (avg), memory (string), uptime (s), prettyName (string), processor (string), isRpi (bool), pigpioVersion (number). The `throttled` field comes from vcgencmd get_throttled.
             *     - **IPFS** (IP1): system diagnostics, DHT routing, pins, listen addresses
             *     - **Roon** (RN1/RN2): host, portCount, pingEnabled, configured; when useRoonApi=true: paired (bool), zoneCount (number), activeZones (number), nowPlaying (string, optional)
             *     - **Alby Hub**: NWC fields when legacyProbe=false (connected, setupCompleted, backendType, appCount)
             *     - **qBittorrent** (QB1): per-torrent stats, speeds, progress, ETA
             *     - **AdGuard Home** (AG1): filtering, clients, DHCP, security features
             *     - **Philips Hue** (X3): lightCount, onCount, offCount with time-series charting
             */
            metrics: {
                [key: string]: number | string | boolean | null;
            };
            /** @description Timestamp (milliseconds since epoch) when snapshot was taken */
            at: number;
        };
        AggregatedEntry: {
            /** @example bitcoin:main */
            id: string;
            kind: string;
            instanceId: string;
            result: {
                /** @constant */
                ok: true;
                value: components["schemas"]["HealthSnapshot"];
            } | {
                /** @constant */
                ok: false;
                error: {
                    code: string;
                    message: string;
                };
            };
        };
        InstanceInfo: {
            id: string;
            kind: string;
            instanceId: string;
        };
        BreakerMetrics: {
            /** @enum {string} */
            state: "closed" | "open" | "half_open";
            successes: number;
            failures: number;
            rejects: number;
            trips: number;
        };
        CacheStats: {
            size: number;
            hits: number;
            misses: number;
        };
        PollerStats: {
            tracked: number;
        };
        MetricsSnapshot: {
            breakers: {
                [key: string]: components["schemas"]["BreakerMetrics"];
            };
            poller: components["schemas"]["PollerStats"] | null;
            cache: {
                [key: string]: components["schemas"]["CacheStats"];
            };
            /** @description Cumulative service poll errors since process start */
            errors: {
                total: number;
                byService: {
                    [key: string]: number;
                };
            };
            process: {
                uptimeSec: number;
                rss: number;
                heapUsed: number;
            };
        };
        SetupStatus: {
            needsSetup: boolean;
            serviceCount: number;
        };
        FieldMeta: {
            name: string;
            label: string;
            /** @enum {string} */
            type: "string" | "number" | "boolean" | "secret" | "url" | "enum";
            required?: boolean;
            secret?: boolean;
            placeholder?: string;
            help?: string;
            options?: string[];
        };
        KindSchema: {
            kind: string;
            label: string;
            description?: string;
            fields: components["schemas"]["FieldMeta"][];
        };
        ServiceInstance: {
            id: string;
            kind: string;
            instanceId: string;
            enabled: boolean;
            /** @description Full service config. Secret field values returned as "***". */
            config: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /**
         * @description Full service-instance config (kind-discriminated). Secrets sent as "***" preserve existing value on update. Request is flat (not nested under "config"); kind determines which additional fields are present.
         * @example {
         *       "kind": "bitcoin",
         *       "instanceId": "main",
         *       "enabled": true,
         *       "cacheTtlMs": 10000,
         *       "timeoutMs": 5000,
         *       "onionUrl": "http://example.onion",
         *       "rpcUser": "bitcoinrpc",
         *       "rpcPassword": "secret123",
         *       "rpcPort": 8332
         *     }
         */
        ServiceInstanceInput: {
            /** @example bitcoin */
            kind: string;
            /** @example main */
            instanceId: string;
            /** @example true */
            enabled: boolean;
            /** @description Per-kind polling behavior (optional) */
            pollPolicy?: {
                [key: string]: unknown;
            };
            /**
             * @description Cache TTL in milliseconds (optional; default 10000)
             * @example 10000
             */
            cacheTtlMs?: number;
            /**
             * @description Request timeout in milliseconds (optional; default 5000)
             * @example 5000
             */
            timeoutMs?: number;
        } & {
            [key: string]: unknown;
        };
        TestConnectionResult: {
            ok: boolean;
            latencyMs?: number;
            error?: string;
        };
        AuditEntry: {
            id: number;
            /** Format: date-time */
            ts: string;
            /** @enum {string} */
            action: "create" | "update" | "delete" | "import" | "export";
            targetKind: string;
            targetId: string;
            actor?: string;
            diff?: {
                [key: string]: unknown;
            };
        };
        ExportBundle: {
            /** @enum {integer} */
            version: 1;
            /** Format: date-time */
            exportedAt: string;
            /** @description Base64 AES-256-GCM ciphertext of JSON service array */
            payload: string;
        };
        ImportResult: {
            imported: number;
            updated: number;
            skipped: number;
            errors: {
                kind: string;
                instanceId: string;
                message: string;
            }[];
        };
        /** @description Per-torrent detail from qBittorrent /api/v2/torrents/info */
        QBittorrentTorrentInfo: {
            /** @description Torrent hash */
            hash?: string;
            /** @description Torrent name */
            name?: string;
            /** @description Torrent state (downloading */
            state?: string;
            /** @description Progress 0..1 */
            progress?: number;
            /** @description Download speed in bytes/sec */
            dlspeed?: number;
            /** @description Upload speed in bytes/sec */
            upspeed?: number;
            /** @description Total size in bytes */
            size?: number;
            /** @description Downloaded bytes */
            downloaded?: number;
            /** @description Uploaded bytes */
            uploaded?: number;
            /** @description ETA seconds */
            eta?: number;
            /** @description Torrent category */
            category?: string;
        };
        /** @description qBittorrent service metrics (QB1 — incremental sync + per-torrent details + logs) */
        QBittorrentStats: {
            /** @description qBittorrent API version */
            version?: string;
            /** @description Uptime in seconds */
            uptime?: number;
            /** @description Total torrent count */
            torrentsTotal: number;
            /** @description Torrents in downloading state */
            torrentsDownloading: number;
            /** @description Torrents in uploading state */
            torrentsSeeding: number;
            /** @description Paused torrents */
            torrentsPaused: number;
            /** @description Completed torrents */
            torrentsCompleted: number;
            /** @description Torrents in error or missingFiles state */
            torrentsError: number;
            /** @description Global download speed in bytes/sec */
            dlSpeed: number;
            /** @description Global upload speed in bytes/sec */
            upSpeed: number;
            /** @description Total downloaded in bytes */
            dlData?: number;
            /** @description Total uploaded in bytes */
            upData?: number;
            /** @description Connection status (connected */
            connectionStatus?: string;
            /** @description Listen port */
            listenPort?: number;
            /** @description DHT node count */
            dhtNodes?: number;
            /** @description Free disk space in bytes */
            freeSpaceOnDisk?: number;
            /** @description Top 20 torrents by combined dl+ul speed (per-torrent sync) */
            activeTorrents: components["schemas"]["QBittorrentTorrentInfo"][];
            /** @description Critical log messages from /api/v2/log/main (type=8) since last poll */
            recentErrors: string[];
            /** @description Warning log messages from /api/v2/log/main (type=4) since last poll */
            recentWarnings: string[];
        };
        /** @description AdGuard Home service metrics (AG1 — extended stats with filtering, clients, DHCP, security features; graceful degradation on optional endpoint failures) */
        AdGuardStats: {
            /** @description AdGuard Home version */
            version?: string;
            /** @description Service running state */
            running?: boolean;
            /** @description DNS protection enabled flag */
            protectionEnabled?: boolean;
            /** @description DNS server port */
            dnsPort?: number;
            /** @description HTTP API port */
            httpPort?: number;
            /** @description Total DNS queries processed */
            totalQueries?: number;
            /** @description Sum of all blocked queries (filtering + safebrowsing + safesearch + parental) */
            blockedQueries?: number;
            /** @description Allowed queries = totalQueries - blockedQueries */
            allowedQueries?: number;
            /** @description Percentage of blocked queries (0–100 */
            blockingRate?: number;
            /** @description Average DNS query processing time (milliseconds) */
            avgProcessingTime?: number;
            /** @description Most-blocked domain name (or 'N/A') */
            topBlockedDomain?: string;
            /** @description Most-queried domain name (or 'N/A') */
            topQueriedDomain?: string;
            /** @description Most-active client IP (or 'N/A') */
            topClient?: string;
            /** @description Queries blocked by SafeBrowsing filter */
            safebrowsingBlocked?: number;
            /** @description Queries blocked by SafeSearch enforcement */
            safesearchBlocked?: number;
            /** @description Queries blocked by Parental Control filter */
            parentalBlocked?: number;
            /** @description Filtering toggle state (null on /control/filtering/status fetch failure) */
            filteringEnabled?: boolean | null;
            /** @description Number of configured filter lists */
            filterCount?: number;
            /** @description Sum of rules from enabled filter lists only (filters with enabled !== false) */
            totalRules?: number;
            /** @description Count of custom user-defined rules */
            userRules?: number;
            /** @description Number of unique clients */
            clientCount?: number;
            /** @description Number of auto-detected clients */
            autoClientCount?: number;
            /** @description DHCP server enabled (null on /control/dhcp/status fetch failure) */
            dhcpEnabled?: boolean | null;
            /** @description Active DHCP leases */
            dhcpLeases?: number;
            /** @description Static DHCP leases */
            dhcpStaticLeases?: number;
            /** @description SafeBrowsing protection enabled (null on /control/safebrowsing/status fetch failure) */
            safebrowsingEnabled?: boolean | null;
            /** @description Parental Control enabled (null on /control/parental/status fetch failure) */
            parentalEnabled?: boolean | null;
            /** @description SafeSearch enforcement enabled (null on /control/safesearch/status fetch failure) */
            safesearchEnabled?: boolean | null;
            /** @description Number of configured upstream DNS servers */
            upstreamCount?: number;
            /** @description Upstream DNS mode (e.g. */
            upstreamMode?: string | null;
        };
    };
    responses: {
        /** @description Domain error */
        DomainError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["DomainError"];
            };
        };
    };
    parameters: {
        /** @description Service kind (e.g. bitcoin, ipfs, homebridge) */
        Kind: string;
        /** @description Instance id. Omit to use first registered instance for the kind. */
        Instance: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
