#!/usr/bin/env python3
"""Validate a generated standalone cloud agreement against vendored inputs."""

from pathlib import Path
import sys

HEADER = "<!-- Generated by dotfiles/Other/codex/generate-cloud-policy.py; do not edit. -->\n\n"


def render(common: str, overlay: str) -> str:
    return HEADER + common.rstrip() + "\n\n" + overlay.rstrip() + "\n"


def main():
    root = Path(__file__).resolve().parent
    expected = render(
        (root / "policy/global.md").read_text(), (root / "policy/cloud.md").read_text()
    )
    if (root / "AGENTS.md").read_text() != expected:
        print(
            "Cloud policy drift: regenerate from the canonical dotfiles source",
            file=sys.stderr,
        )
        return 1
    print("Cloud policy: generated agreement matches vendored source inputs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
