#!/usr/bin/env bash
# Runs once when the devcontainer is first created, as the `dev` user.
# Installs JS deps, seeds the Claude config, and prepares git for signed commits.
#
# NOTE: all privileged setup (perms repair, egress proxy, firewall) happens in
# the root ENTRYPOINT (/usr/local/sbin/watchman-entrypoint) BEFORE this runs.
# The container has no-new-privileges, so there is no sudo here.

set -euo pipefail
cd /workspaces/Watchman

# Wait for the egress proxy (started by the root entrypoint) before any network
# install — postCreate can race the entrypoint's proxy startup, and with egress
# locked to the proxy UID, installs fail until 127.0.0.1:3128 is listening.
echo "[post-create] Waiting for egress proxy on 127.0.0.1:3128..."
for _ in $(seq 1 30); do
  (exec 3<>/dev/tcp/127.0.0.1/3128) 2>/dev/null && break
  sleep 1
done

# Supply-chain protection: install Aikido safe-chain so package installs are
# screened against its malware list (malware-list.aikido.dev, allowlisted in
# squid). `safe-chain setup` writes shell wrappers; BASH_ENV (devcontainer.json)
# sources them into every bash session so npm/bun/pip installs Claude runs
# mid-session are screened. The project's own pinned deps below are installed
# plain (already vetted via the lockfile) to avoid first-boot fragility.
echo "[post-create] Installing safe-chain (supply-chain protection)..."
if npm install -g @aikidosec/safe-chain >/dev/null 2>&1 && command -v safe-chain >/dev/null 2>&1; then
  safe-chain setup >/dev/null 2>&1 || true
  echo "[post-create] safe-chain installed (screens npm/bun/pip in later sessions)."
else
  echo "[post-create] WARN: safe-chain install failed — continuing without it." >&2
fi

# Install JS deps (npm honors HTTPS_PROXY → squid → registry.npmjs.org).
# `npm ci` is the reproducible install: it builds strictly from package-lock.json
# and fails loudly on a stale lock (the signal we want, matching the pinned
# base image / devcontainer-lock).
echo "[post-create] npm ci..."
npm ci

# Local .env — only generated if missing. The master key is intentionally left
# unset: fill it in via a container-only mechanism if needed (this file lives on
# the bind-mounted workspace, i.e. on the host disk too).
if [[ ! -f apps/backend/.env ]]; then
  echo "[post-create] Writing apps/backend/.env (devcontainer defaults)..."
  cat > apps/backend/.env <<'EOF'
# Generated by .devcontainer/post-create.sh — safe to edit.
NODE_ENV=development
BACKEND_V2_HOST=0.0.0.0
BACKEND_V2_PORT=3001
LOG_LEVEL=info
DATA_DIR=./data

# Required: AES-256-GCM master key for service-secret encryption at rest.
# Regenerate with: openssl rand -base64 32
WATCHMAN_MASTER_KEY=
EOF
fi

# Build a writable ~/.gitconfig that:
#   - includes the read-only bind-mounted host gitconfig (so user.name,
#     user.email, aliases, etc. carry over without us hardcoding them)
#   - declares /workspaces/Watchman as a safe.directory (the bind mount
#     ends up with non-dev ownership, which git would otherwise reject)
if [[ ! -f /home/dev/.gitconfig || ! -s /home/dev/.gitconfig ]]; then
  cat > /home/dev/.gitconfig <<'EOF'
[include]
    path = /home/dev/.gitconfig-host
[safe]
    directory = /workspaces/Watchman
# Override the host's signingkey path — that path (/Users/.../ssh/github.pub)
# doesn't resolve inside the container. The public key is bind-mounted to a
# container-local path, and the corresponding private key stays on the host;
# ssh-keygen reaches it through SSH_AUTH_SOCK (Docker Desktop forwards the
# host's ssh-agent into the container).
[user]
    signingkey = /home/dev/.ssh/host-signing.pub
EOF
fi

# Seed the container's ~/.claude + ~/.claude.json from the SANITIZED staging
# dir the host wrapper produced at /home/dev/.claude-stage (bind RO):
#   /home/dev/.claude-stage/dot-claude/   sanitized copy of host ~/.claude
#   /home/dev/.claude-stage/claude.json   sanitized copy of host ~/.claude.json
# The host wrapper strips secrets (.credentials.json) and active code-exec
# config (hooks/mcpServers/enabledPlugins) before staging, so a compromised
# host config can't silently propagate executable config into the container.
STAGE=/home/dev/.claude-stage
if [[ ! -f /home/dev/.claude/settings.json && -d "$STAGE/dot-claude" ]]; then
  echo "[post-create] Seeding ~/.claude from sanitized stage..."
  if ! rsync -a --ignore-errors "$STAGE/dot-claude/" /home/dev/.claude/; then
    echo "[post-create] WARN: ~/.claude rsync seed had errors (some files may be missing)." >&2
  fi
  echo "[post-create] Seeded $(find /home/dev/.claude -mindepth 1 -maxdepth 1 | wc -l) entries into ~/.claude."
fi
if [[ ! -f /home/dev/.claude.json && -f "$STAGE/claude.json" ]]; then
  cp "$STAGE/claude.json" /home/dev/.claude.json
  chmod 0600 /home/dev/.claude.json
fi

# gh authenticates via GH_TOKEN forwarded from the host Keychain by the wrapper
# (no persistent token volume). If it's absent, gh read/write still needs auth.
if ! gh auth status >/dev/null 2>&1; then
  cat <<'NOTE'
[post-create] gh is not authenticated. The wrapper forwards GH_TOKEN from your
              host Keychain entry `watchman-gh-token` if present. To set it up,
              on the HOST run once:
                gh auth token | security add-generic-password \
                  -s watchman-gh-token -a "$USER" -w
              (or paste a PAT). Then re-run `watchman-claude`.
NOTE
fi

echo "[post-create] Done."
echo "[post-create] Start the stack with:  npm run dev"
echo "[post-create] Start Claude with:     claude --dangerously-skip-permissions"
